### ISSUE TITLE
Cannot view entities in TF2 VScript maps?

### ISSUE THREAD

**Issue by Chdata** [jakgor471/BSPEntSpy#1]
I'm trying to use bspentspy to see how the entities are arranged in Team Fortress 2 maps that use VScript.

It seems the program can open other maps just fine, but trying it on the recent vsh_ maps added to the game, it cannot view the entities.

Other versions of entspy (0.8 and the CS:GO version) I've tried also fail to load them.

**Comment by jakgor471** [comment]
could you please provide me with the exact BSP file name? I will test it and try to fix the issue. Thanks for reporting.
EDIT: I've already found the maps. Yes, indeed, they do not work. I'll try to fix it ASAP

**Comment by jakgor471** [comment]
Problem identified. The new BSP format for Team Fortess 2 uses LZMA compression for entities. I'm working on that

**Comment by jakgor471** [comment]
The issue is fixed. Please see the latest version (v1.2). If any other error comes up - please create a new issue. Once again - thank you for reporting.

**Comment by Chdata** [comment]
Thanks much! Looks like it works great!
