### ISSUE TITLE
Support for Goldsrc BSPs?

### ISSUE THREAD

**Issue by ljcool2006** [jakgor471/BSPEntSpy#2]
I am currently looking for an entity lump editor that supports Goldsrc (I have a map that the original author lost the VMF of). Perhaps this could be the first editor to support it?

**Comment by ljcool2006** [comment]
Ignore that, I just [found one](https://gamebanana.com/tools/5061).

**Comment by jakgor471** [comment]
I'll try to implement support for GoldSrc BSP. Thanks for your input and I'm happy you've found the solution to your problem. I hope in a near future my program will be of any use for you too :)

**Comment by jakgor471** [comment]
Hi, if you're still there - the support for GoldSrc has been added. Thank you for your suggestion 👍
